- id: Tar
  to: Tar III - Secure Commerce Commission Depository
  from:
    - name: Jita IV - Moon 4 - Caldari Navy Assembly Plant
      vol_cost: 150
      isk_cost: 0.007
    - name: Dodixie IX - Moon 20 - Federation Navy Assembly Plant
    - name: Botane - IChooseYou Market and Industry
    - name: Hek VIII - Moon 12 - Boundless Creation Factory
- id: Dodixie
  to: Dodixie IX - Moon 20 - Federation Navy Assembly Plant
  from:
    - name: Jita IV - Moon 4 - Caldari Navy Assembly Plant
      vol_cost: 150
      isk_cost: 0.007
    - name: Botane - IChooseYou Market and Industry
    - name: Hek VIII - Moon 12 - Boundless Creation Factory
